### ISSUE TITLE
能否拦截html做内容转换？

### ISSUE THREAD

**Issue by rainmanhhh** [Windson1806/vite-plugin-virtual-html#1]
比如我想给html里面的url路径都加上时间戳（cache  busting)

**Comment by Windson1806** [comment]
没有考虑通过这个插件来实现这种操作.我写这个插件的目的主要是用于在多页面应用下将原本需要放在项目根目录的html文件放到各个页面模块内.这样子可以方便页面的管理.也比较符合我开发vue项目的模式.

这是我的第一个开源项目,谢谢支持~

**Comment by imguolao** [comment]
我可以 pr 提供这个功能，考虑合入此功能吗？

我现在为了实现注入 html 需要额外安装其他插件或者自己写一个插件，都很麻烦，我想在同一个插件里面对 html 完成 transform。

**Comment by WindsonFF** [comment]
可以呀.
